"""Vendor a standalone PNG decoder from LVGL's patched lodepng.

LVGL does not ship stock lodepng - it rewires the decoder to allocate lv_draw_buf_t
through the LVGL image cache, does its file I/O through lv_fs, and wraps the whole
translation unit in #if LV_USE_LODEPNG. Borrowing it from a worker thread is what
crashed a device: lodepng_decode32() hands back a STRUCT pointer, not pixels.

This produces ui/pngdec.c + ui/pngdec.h - the same well-tested decoder with the four
LVGL couplings reverted to their upstream form:

  1. the #if LV_USE_LODEPNG wrapper and lv_global include        -> removed
  2. lv_malloc / lv_realloc / lv_free / lv_memcpy / lv_memset    -> libc
  3. the lv_fs disk helpers                                      -> excluded
  4. the lv_draw_buf output allocation in decodeGeneric+decode   -> lodepng_malloc

LV_USE_LODEPNG goes back to 0, so LVGL's own copy compiles to an empty object and
there is no duplicate-symbol clash with this one.
"""
import re, io, os

SRC_C = r"F:\diskos\ui\lvgl\src\libs\lodepng\lodepng.c"
SRC_H = r"F:\diskos\ui\lvgl\src\libs\lodepng\lodepng.h"
DST_C = r"F:\diskos\ui\pngdec.c"
DST_H = r"F:\diskos\ui\pngdec.h"

HDR = """/* SPDX-License-Identifier: Zlib */
/* lodepng by Lode Vandevenne - Copyright (c) 2005-2022, zlib licence.
 *
 * VENDORED FOR diskOS, generated by scratch/mk_pngdec.py - do not hand-edit.
 *
 * This is LVGL's copy of lodepng with its LVGL couplings reverted to upstream:
 * the LV_USE_LODEPNG wrapper is gone, allocation is libc rather than lv_malloc /
 * lv_draw_buf, and the lv_fs disk helpers are excluded.
 *
 * WHY a second copy exists: LVGL patches decodeGeneric() to return an lv_draw_buf_t*
 * instead of a pixel buffer, allocated through the LVGL image cache. Calling that from
 * an art worker thread and treating the result as pixels corrupted the heap and
 * hard-rebooted a device on 2026-09-06. This copy has no LVGL dependency at all, so it
 * is safe off the LVGL thread - which is exactly where album art is decoded.
 */
"""

# ---------------------------------------------------------------- header
h = open(SRC_H, encoding="utf-8", errors="replace").read().replace("\r\n", "\n")
h = h.replace('#include "../../../lvgl.h"\n#if LV_USE_LODEPNG\n#include LV_STDDEF_INCLUDE /*for size_t*/\n'
              'LV_ATTRIBUTE_EXTERN_DATA extern const char * LODEPNG_VERSION_STRING;',
              '#include <stddef.h> /*for size_t*/\nextern const char * LODEPNG_VERSION_STRING;')
h = h.replace("#endif /*LV_USE_LODEPNG*/\n", "")
h = h.replace("LODEPNG_H", "DISKOS_PNGDEC_H")
# Any remaining LVGL attribute macros - they only decorate declarations.
h = h.replace("LV_ATTRIBUTE_EXTERN_DATA ", "")
# Disk I/O is LVGL-FS based upstream here; we never want it, and defining this
# in the HEADER keeps the pair self-contained rather than needing a Makefile flag.
h = h.replace("#ifndef DISKOS_PNGDEC_H", "#define LODEPNG_NO_COMPILE_DISK 1\n#ifndef DISKOS_PNGDEC_H", 1)
assert "LV_USE_LODEPNG" not in h, "header still references LV_USE_LODEPNG"
assert "lvgl.h" not in h, "header still includes lvgl.h"
assert "LV_ATTRIBUTE" not in h, "header still has LVGL attribute macros"
open(DST_H, "w", encoding="utf-8", newline="\n").write(HDR + h)
print("wrote pngdec.h (%d lines)" % h.count("\n"))

# ---------------------------------------------------------------- source
c = open(SRC_C, encoding="utf-8", errors="replace").read().replace("\r\n", "\n")

c = c.replace('#include "lodepng.h"\n#if LV_USE_LODEPNG\n#include "../../core/lv_global.h"\n\n'
              '#define image_cache_draw_buf_handlers &(LV_GLOBAL_DEFAULT()->image_cache_draw_buf_handlers)\n',
              '#include "pngdec.h"\n#include <string.h> /* memcpy/memset */\n')
c = c.replace("#endif /*LV_USE_LODEPNG*/\n", "")

# 2. allocators back to libc
for a, b in (("lv_malloc(", "malloc("), ("lv_realloc(", "realloc("), ("lv_free(", "free("),
             ("lv_memcpy(", "memcpy("), ("lv_memset(", "memset(")):
    c = c.replace(a, b)

# 4a. decodeGeneric output allocation -> upstream
old = """    if(!state->error) {
        lv_draw_buf_t * decoded = lv_draw_buf_create_ex(image_cache_draw_buf_handlers, *w, *h, LV_COLOR_FORMAT_ARGB8888, 4 * *w);
        if(decoded) {
            *out = (unsigned char*)decoded;
            outsize = decoded->data_size;
        }
        else state->error = 83; /*alloc fail*/
    }
    if(!state->error) {
        lv_draw_buf_t * decoded = (lv_draw_buf_t *)*out;
        lodepng_memset(decoded->data, 0, outsize);
        state->error = postProcessScanlines(decoded->data, scanlines, *w, *h, &state->info_png);
    }"""
new = """    if(!state->error) {
        /* diskOS: upstream allocation. LVGL's copy returns an lv_draw_buf_t here; we
         * hand back a plain pixel buffer, which is what every caller expects. */
        outsize = lodepng_get_raw_size(*w, *h, &state->info_png.color);
        *out = (unsigned char *)lodepng_malloc(outsize);
        if(!*out) state->error = 83; /*alloc fail*/
    }
    if(!state->error) {
        lodepng_memset(*out, 0, outsize);
        state->error = postProcessScanlines(*out, scanlines, *w, *h, &state->info_png);
    }"""
assert c.count(old) == 1, "decodeGeneric block not found exactly once"
c = c.replace(old, new)

# 4b. the colour-conversion branch in lodepng_decode -> upstream
old2 = """        lv_draw_buf_t * old_buf = (lv_draw_buf_t *)*out;

        /*TODO: check if this works according to the statement in the documentation: "The converter can convert
        from grayscale input color type, to 8-bit grayscale or grayscale with alpha"*/
        if(!(state->info_raw.colortype == LCT_RGB || state->info_raw.colortype == LCT_RGBA)
           && !(state->info_raw.bitdepth == 8)) {
            return 56; /*unsupported color mode conversion*/
        }

        lv_draw_buf_t * new_buf = lv_draw_buf_create_user(image_cache_draw_buf_handlers,*w, *h, LV_COLOR_FORMAT_ARGB8888, 4 * *w);
        if(new_buf == NULL) {
            state->error = 83; /*alloc fail*/
        }
        else {
            state->error = lodepng_convert(new_buf->data, old_buf->data,
                                            &state->info_raw, &state->info_png.color, *w, *h);

            if (state->error) {
                lv_draw_buf_destroy(new_buf);
                new_buf = NULL;
            }
        }

        *out = (unsigned char*)new_buf;
        lv_draw_buf_destroy(old_buf);"""
new2 = """        /* diskOS: upstream conversion path - plain buffers, no lv_draw_buf. */
        unsigned char * data = *out;
        size_t outsize_conv;

        /*TODO: check if this works according to the statement in the documentation: "The converter can convert
        from grayscale input color type, to 8-bit grayscale or grayscale with alpha"*/
        if(!(state->info_raw.colortype == LCT_RGB || state->info_raw.colortype == LCT_RGBA)
           && !(state->info_raw.bitdepth == 8)) {
            lodepng_free(data);
            *out = NULL;
            return 56; /*unsupported color mode conversion*/
        }

        outsize_conv = lodepng_get_raw_size(*w, *h, &state->info_raw);
        *out = (unsigned char *)lodepng_malloc(outsize_conv);
        if(!(*out)) {
            state->error = 83; /*alloc fail*/
        }
        else {
            state->error = lodepng_convert(*out, data, &state->info_raw, &state->info_png.color, *w, *h);
            if(state->error) { lodepng_free(*out); *out = NULL; }
        }
        lodepng_free(data);"""
assert c.count(old2) == 1, "lodepng_decode conversion block not found exactly once"
c = c.replace(old2, new2)

if "lv_draw_buf_create" in c or "lv_draw_buf_destroy" in c or "lv_draw_buf_t *" in c:
    print("REMAINING lv_draw_buf lines:")
    for i, l in enumerate(c.splitlines(), 1):
        if "lv_draw_buf_create" in l or "lv_draw_buf_destroy" in l or "lv_draw_buf_t *" in l: print("   %d: %s" % (i, l.strip()[:120]))
    raise SystemExit("lv_draw_buf still referenced")

assert "LV_USE_LODEPNG" not in c, "LV_USE_LODEPNG still referenced"
assert "image_cache_draw_buf_handlers" not in c, "LVGL image cache still referenced"
# lv_fs_* only lives inside LODEPNG_COMPILE_DISK, which we never define.
open(DST_C, "w", encoding="utf-8", newline="\n").write(HDR + c)
print("wrote pngdec.c (%d lines)" % c.count("\n"))
print("remaining lv_ refs (should only be lv_fs inside the DISK block):",
      len(re.findall(r"\blv_[a-z_]+\(", c)))
