/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright (C) 2026 diskOS contributors */
#include "screens.h"
#include "buildid.h"   /* generated by the Makefile: DISKOS_BUILD */
#include <stdio.h>
#include <string.h>
#include <unistd.h>   /* access() for the updates flag */

/* About (SCR_ABOUT): what this device is running. Opened from Settings -> System ->
 * About.
 *
 * The row that earns its place here is Build. Two entries in CLAUDE.md's symptom table
 * are "my change did nothing" turning out to be the wrong binary on the device - an x86
 * build that could not start, or a hand-deployed one that reverted on reboot - and until
 * now the only way to tell was to SSH in and hash /usr/data/mq_ui. A compile timestamp on
 * screen answers it in two taps.
 *
 * Everything here is either baked in at compile time or read once on entry. Nothing on
 * this screen polls. */

static lv_obj_t *g_val_fw;
static lv_obj_t *g_val_updates;

/* One "KEY / value" pair, stacked, matching the Song Info layout. */
static lv_obj_t *about_row(lv_obj_t *list, const char *key, const char *val)
{
    lv_obj_t *cell = lv_obj_create(list);
    lv_obj_remove_style_all(cell);
    lv_obj_set_width(cell, 244);
    lv_obj_set_height(cell, LV_SIZE_CONTENT);
    lv_obj_set_flex_flow(cell, LV_FLEX_FLOW_COLUMN);
    lv_obj_clear_flag(cell, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *k = lv_label_create(cell);
    lv_label_set_text(k, key);
    lv_obj_set_style_text_font(k, th_font(14), 0);
    lv_obj_set_style_text_color(k, th_text3(), 0);

    lv_obj_t *v = lv_label_create(cell);
    lv_obj_set_width(v, 244);
    lv_label_set_long_mode(v, LV_LABEL_LONG_WRAP);
    lv_label_set_text(v, val);
    lv_obj_set_style_text_font(v, th_font(16), 0);
    lv_obj_set_style_text_color(v, th_text(), 0);
    return v;
}

void about_create(lv_obj_t *root)
{
    lv_obj_set_style_bg_color(root, th_bg(), 0);
    lv_obj_set_style_bg_opa(root, LV_OPA_COVER, 0);

    ui_header(root, "About");

    /* 244 wide, inset 58: the screen is a 360px CIRCLE, so a list that reaches y=300
     * has to sit inside the chord there (~264px), not inside the bounding box. */
    lv_obj_t *list = lv_obj_create(root);
    lv_obj_remove_style_all(list);
    lv_obj_set_pos(list, 58, 74);
    lv_obj_set_size(list, 244, 236);
    lv_obj_set_style_bg_opa(list, LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_bottom(list, 28, 0);
    lv_obj_set_style_pad_row(list, 14, 0);
    lv_obj_set_flex_flow(list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_scroll_dir(list, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(list, LV_SCROLLBAR_MODE_OFF);
    lv_obj_add_flag(list, LV_OBJ_FLAG_SCROLL_MOMENTUM);

    about_row(list, "diskOS", "beta");
    about_row(list, "Build", DISKOS_BUILD);
    g_val_fw      = about_row(list, "Player firmware", "-");
    g_val_updates = about_row(list, "On-Device Updates", "-");
    about_row(list, "Licence", "GPL-3.0-or-later");
}

/* Read the two live values. Called on entry rather than on a timer: the firmware string
 * cannot change while running, and the updates flag only changes from the row two screens
 * back, so re-reading on entry is both sufficient and free. */
void about_refresh(void)
{
    if(!g_val_fw) return;

    char fw[64] = "-";
    FILE *f = fopen("/etc/product_version/version.in", "r");
    if(f){
        char line[128];
        while(fgets(line, sizeof line, f)){
            char *p = strstr(line, "MAIN_OS_VER");
            if(!p) continue;
            p = strchr(p, '=');
            if(!p) continue;
            p++;
            while(*p == ' ' || *p == '"') p++;
            size_t n = strcspn(p, "\"\r\n");
            if(n >= sizeof fw) n = sizeof fw - 1;
            memcpy(fw, p, n); fw[n] = 0;
            break;
        }
        fclose(f);
    }
    lv_label_set_text(g_val_fw, fw[0] ? fw : "-");

    /* The FILE is the truth here, exactly as it is for S97 - see apply_updates in
     * settings.c. Showing the config row's copy instead could disagree with what the
     * boot installer will actually find. */
    lv_label_set_text(g_val_updates,
                      access("/usr/data/diskos_updates_enabled", F_OK) == 0 ? "On" : "Off");
}
